### PR TITLE
Changes VIRTUAL_HOST env variable for nginx container

### PR DESCRIPTION
**Pull request by mathewpeterson**
Sorry about that.

### CODE REVIEW

**Comment by drgomesp** [comment]
Merged and fixed tag, but it still doesn't work with http://symfony-docker.local:8888 or 80

**Comment by mathewpeterson** [comment]
Correct, you need to have something like [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) running. This is a http reverse proxy and will allow you to have multiple projects running all on port 80.

I have created [my-docker-environment](https://github.com/mathewpeterson/my-docker-environment) repository that packages some of this stuff together so you don't even need to edit your `/etc/hosts` file.

**Comment by drgomesp** [comment]
Also, we need to specify the /app volume to be built with www-data as owner, instead of my local volume owner. This causes the "Failed to write cache" issue. Any ideas?

**Comment by mathewpeterson** [comment]
That has been address in #27

**Pull request merged**
